### PR TITLE
Portfolio V2

### PR DESCRIPTION
**Pull request by DevKaranJ**
Use of template 3
update with contact form 
animation
reponsive site

### CODE REVIEW

**Review by bellom — CHANGES_REQUESTED** [review]
Hi @DevKaranJ 

### This is a manual review

Request Changes :+1:

It was stated in the email that you should make sure to implement according to the [project requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md#:~:text=Minimum%20mobile%20screen%20size%20should%20be%20375px). 

Your design below doesn't match the given design;
image

1. Follow the responsiveness guide - [here](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md#:~:text=The%20website%20should%20be%20responsive%2C%20following%20these%20breakpoints%3A)
2. Remove the horizontal scroll on your page.

Given design:
[Link](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=1-468&t=19kJHZ4o6jJbN0VK-0)

Please implement your design accordingly and resubmit for review again.

Cheers and Happy coding!:clap::clap::clap:

**Comment by DevKaranJ** [comment]
I wanted to inform you that I have addressed the changes requested in the pull request. I have implemented the necessary modifications and improvements according to our previous discussions and your feedback.

**Comment by bellom** [comment]
@DevKaranJ,

### This is a manual review.

Great job working on the requested changes.

# Approved :+1:

Cheers, and Happy coding!:clap::clap::clap:

**Comment by bellom** [comment]
@DevKaranJ - Please go ahead and merge!

**Pull request merged**
